import {useMemo,type ReactNode} from "react";
import {AbsoluteFill,Easing,interpolate,spring,useCurrentFrame,useVideoConfig} from "remotion";
import {Character,type CharacterProps} from "../components/Character";
import {MotionDesignSystem,EntityMark,type VisualPrimitive,type VisualOperation,type VisualState,type CompositionMode,type EntityIconMap,type ModelRelation} from "./MotionDesignSystem";
import {SemanticScene,type RepresentationMode,type SceneBlueprint,type SemanticActionWindow,type SemanticEntity} from "./SemanticScene";

export type ExplanationRole="character-hook"|"diagram-build"|"process-flow"|"object-state-change"|"comparison"|"kinetic-emphasis"|"character-reaction"|"recap";
export interface ExplanationSceneProps{
  role?:ExplanationRole;visualOperation?:VisualOperation;visualPrimitive?:VisualPrimitive;visualState?:VisualState;numericValue?:number|null;compositionMode?:CompositionMode;
  title?:string;keyText?:string;elements?:string[];entityIdentityKeys?:string[];entityIcons?:EntityIconMap;modelRelations?:ModelRelation[];before?:string;after?:string;
  characterCutIn?:"none"|"speaker"|"listener"|"both";soundCue?:string;characters?:CharacterProps[];rendererDiagnosticMode?:"normal"|"foreground-only"|"background-only";
  representationMode?:RepresentationMode;sceneBlueprint?:SceneBlueprint;visualClaim?:string;semanticActionWindows?:SemanticActionWindow[];semanticEntities?:SemanticEntity[];semanticFallback?:boolean;semanticRepresentation?:SemanticRenderExtension;
}
const BG="#08101E",PAPER="#F7F4EA",ACCENT="#FFD166",GREEN="#7DE2A8",RED="#FF7D7D";
type SemanticRenderExtension={representationMode?:RepresentationMode;sceneBlueprint?:SceneBlueprint;visualClaim?:string;semanticActionWindows?:SemanticActionWindow[];semanticEntities?:SemanticEntity[];semanticFallback?:boolean};
const PRIMITIVE_GLOW:Partial<Record<VisualPrimitive,string>>={particles:"#4169A8",rays:"#2D8FB8",wave:"#4E63C8",horizon:"#3D8B72",spectrum:"#9158A8",path:"#2C7A9C",shells:"#5A739E",objects:"#354D78",network:"#275E78",hierarchy:"#594B8A","one-to-many":"#386F92","many-to-one":"#386F92","facets-around-center":"#77518E","overlapping-sets":"#665099","nested-context":"#4A628F",cycle:"#2C7781","cause-chain":"#356D92","before-after":"#536B87",map:"#276F68",timeline:"#315F8B",quantity:"#715B36","physical-transformation":"#5E4F89"};
function backgroundField(p:VisualPrimitive,g:string){if(["map","path","timeline","cause-chain"].includes(p))return{backgroundImage:`linear-gradient(118deg,transparent 18%,${g}2B 19%,transparent 21%,transparent 48%,${g}20 49%,transparent 51%)`,backgroundSize:"440px 440px"};if(["network","facets-around-center","one-to-many","many-to-one","overlapping-sets"].includes(p))return{backgroundImage:`radial-gradient(circle,${g}55 1.5px,transparent 2px)`,backgroundSize:"46px 46px"};if(["hierarchy","nested-context","shells","objects"].includes(p))return{backgroundImage:`linear-gradient(${g}35 1px,transparent 1px),linear-gradient(90deg,${g}35 1px,transparent 1px)`,backgroundSize:"72px 72px"};return{backgroundImage:`radial-gradient(ellipse at 30% 35%,${g}36,transparent 42%),radial-gradient(ellipse at 75% 62%,${g}20,transparent 38%)`,backgroundSize:"100% 100%"}}
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
function BustReactionPanel({characters=[],mode="none",width:widthOverride,scale=1.4}:Pick<ExplanationSceneProps,"characters">&{mode?:string;width?:number;scale?:number}){if(mode==="none")return null;const selected=characters.filter(c=>mode==="both"||(mode==="speaker"?c.isSpeaking:mode==="listener"?!c.isSpeaking:false)).slice(0,mode==="both"?2:1),width=widthOverride??(mode==="both"?620:360),spread=mode==="both"?width*.484:0;return <div style={{position:"absolute",right:48,top:94,bottom:168,width,overflow:"hidden",borderRadius:38,zIndex:8,background:"linear-gradient(180deg,#21365F 0%,#101A31 100%)",border:"3px solid #65C7F766",boxShadow:"0 24px 70px #0008"}}><div style={{position:"absolute",inset:0,background:"radial-gradient(circle at 50% 35%,#65C7F722,transparent 62%)"}}/>{selected.map((c,i)=><Character key={c.characterId||i} {...c} x={mode==="both"?-spread/2+i*spread:-70} y={430} scale={scale}/>)}</div>}
function CharacterModelInteraction({operation,state,visible}:{operation:VisualOperation;state:VisualState;visible:boolean}){const frame=useCurrentFrame(),{fps,durationInFrames}=useVideoConfig();if(!visible)return null;const reach=interpolate(frame,[fps*.2,fps*.85],[0,1],clamp),consequence=interpolate(frame,[durationInFrames*.72,durationInFrames*.9],[0,1],clamp),y=operation==="compress"?410:operation==="group"?330:operation==="payoff"?270:365,tentative=state==="hypothesis",breaking=state==="contradiction",targetX=1180-reach*250+(breaking?consequence*70:0),targetY=y-(breaking?consequence*34:0),stroke=breaking?RED:ACCENT;return <svg data-character-model-interaction="true" viewBox="0 0 1920 1080" style={{position:"absolute",inset:0,zIndex:7,pointerEvents:"none"}}><path d={`M1510 520 Q${1380-reach*120} ${y-80} ${targetX} ${targetY}`} fill="none" stroke={stroke} strokeWidth={8} strokeLinecap="round" strokeDasharray={tentative?"10 14":"18 16"} opacity={.15+reach*.5}/><circle cx={targetX} cy={targetY} r={12+reach*10} fill={stroke}/></svg>}
type CompositionProps={children:ReactNode;characters:CharacterProps[];cutIn:"none"|"speaker"|"listener"|"both";opacity:number};
function ContentStage({children,right,opacity}:{children:ReactNode;right:number;opacity:number}){return <div style={{position:"absolute",left:56,top:38,right,bottom:132,display:"flex",flexDirection:"column",justifyContent:"center",opacity}}>{children}</div>}
// Narrower panel and smaller character scale than ReactionComposition's
// "both" case (620/1.4): a prior watchability pass found the diagram
// cramped at the ORIGINAL right=610 margin and "fixed" it by silently
// stripping characters from bookend scenes entirely (see hybrid-visual-
// assets.ts's removed shouldPromoteToFullCanvas). Reducing the panel to
// 500/scale 1.05 first (rendered and inspected directly) before touching
// this margin: a first attempt shrinking the panel to 440 while keeping
// scale 1.4 made the two characters visibly overlap and clipped Buddy's
// hair against the panel's rounded top -- shrinking scale alongside width
// fixed both at once, since a smaller character is both narrower (less
// overlap) and shorter (less likely to clip the vertical frame). This
// keeps both characters clearly visible -- the actual point of a bookend
// scene -- while still giving the diagram a real, if modest, width gain
// over the pre-fix 610 margin.
function BookendComposition({children,characters,opacity}:CompositionProps){return <><ContentStage right={580} opacity={opacity}>{children}</ContentStage><BustReactionPanel characters={characters} mode="both" width={500} scale={1.05}/></>}
function FullModelComposition({children,opacity}:CompositionProps){return <ContentStage right={56} opacity={opacity}>{children}</ContentStage>}
function ReactionComposition({children,characters,cutIn,opacity}:CompositionProps){const m=cutIn==="none"?"listener":cutIn;return <><ContentStage right={m==="both"?610:380} opacity={opacity}>{children}</ContentStage><BustReactionPanel characters={characters} mode={m}/></>}
function CompositionFrame(p:CompositionProps&{mode:CompositionMode}){return p.mode==="bookend"?<BookendComposition {...p}/>:p.mode==="reaction"?<ReactionComposition {...p}/>:<FullModelComposition {...p}/>}
function Title({children}:{children?:string}){return children?<div style={{fontSize:60,fontWeight:840,letterSpacing:-1.1,color:PAPER,marginBottom:20,maxWidth:1450}}>{children}</div>:null}
export function mechanismChainAppearAt(resolve:number,i:number){return Math.max(0,Math.min(1,(resolve-i*.2)/(1-i*.2)))}
function MechanismChain({elements,entityIdentityKeys,entityIcons,resolve}:{elements:string[];entityIdentityKeys:string[];entityIcons:EntityIconMap;resolve:number}){const entities=elements.slice(0,3);if(entities.length<2)return null;const xs=entities.length===3?[130,300,470]:[150,450];return <svg viewBox="0 0 600 130" style={{width:Math.min(560,entities.length===3?560:420),height:122,display:"block",margin:"0 auto 20px",overflow:"visible"}}>{entities.slice(1).map((_,i)=><line key={i} x1={xs[i]!+40} y1="65" x2={xs[i+1]!-40} y2="65" stroke={GREEN} strokeWidth="5" opacity={mechanismChainAppearAt(resolve,i+1)}/>)}{entities.map((label,i)=>{const id=entityIdentityKeys[i]||label;return <g key={id} opacity={mechanismChainAppearAt(resolve,i)}><circle cx={xs[i]} cy="65" r="46" fill="#0B1424" stroke={GREEN} strokeWidth="3"/><EntityMark id={id} icon={entityIcons[id]} color={GREEN} x={xs[i]!} y={65} size={30}/></g>})}</svg>}
function PayoffResolution({after,keyText,elements=[],entityIdentityKeys=[],entityIcons={}}:{after?:string;keyText?:string;elements?:string[];entityIdentityKeys?:string[];entityIcons?:EntityIconMap}){const frame=useCurrentFrame(),{fps,durationInFrames}=useVideoConfig(),at=Math.max(fps*.8,durationInFrames*.62),resolve=interpolate(frame,[at,Math.max(at+1,durationInFrames-1)],[0,1],{...clamp,easing:Easing.inOut(Easing.cubic)}),ring=spring({frame:frame-at,fps,config:{damping:15,stiffness:74}});if(resolve<=0)return null;return <div style={{position:"absolute",inset:0,zIndex:8,display:"grid",placeItems:"center",background:`radial-gradient(circle at 50% 48%,rgba(9,22,40,${.5+resolve*.24}),rgba(5,8,16,${resolve*.9}))`,opacity:resolve}}><div style={{position:"absolute",width:420+ring*330,height:420+ring*330,borderRadius:"50%",border:`10px solid ${GREEN}`,opacity:.16+resolve*.38}}/><div data-payoff-copy="single" style={{textAlign:"center",maxWidth:1080,padding:"0 44px"}}><MechanismChain elements={elements} entityIdentityKeys={entityIdentityKeys} entityIcons={entityIcons} resolve={resolve}/><div style={{color:ACCENT,fontSize:72,lineHeight:1.02,fontWeight:930}}>{keyText||after}</div></div></div>}

export const ExplanationScene:React.FC<ExplanationSceneProps>=({role="diagram-build",visualOperation="timeline",visualPrimitive="objects",visualState="mechanism",numericValue=null,compositionMode="full-model",title="",keyText="",elements=[],entityIdentityKeys=[],entityIcons={},modelRelations=[],before="",after="",characterCutIn="none",characters=[],rendererDiagnosticMode="normal",representationMode,sceneBlueprint,visualClaim="",semanticActionWindows=[],semanticEntities=[],semanticRepresentation})=>{
  const effectiveRepresentationMode=representationMode??semanticRepresentation?.representationMode,effectiveBlueprint=sceneBlueprint??semanticRepresentation?.sceneBlueprint,effectiveClaim=visualClaim||semanticRepresentation?.visualClaim||"",effectiveWindows=semanticActionWindows.length?semanticActionWindows:(Array.isArray(semanticRepresentation?.semanticActionWindows)?semanticRepresentation!.semanticActionWindows!:[]),effectiveEntities=semanticEntities.length?semanticEntities:(Array.isArray(semanticRepresentation?.semanticEntities)?semanticRepresentation!.semanticEntities!:[]);
  const frame=useCurrentFrame(),{fps}=useVideoConfig(),progress=interpolate(frame,[0,fps*.25],[0,1],clamp),characterDominant=compositionMode==="bookend"||role==="character-hook"||role==="character-reaction",safeCharacters=useMemo(()=>characters.map(c=>({...c,x:0,y:0})),[characters]),isSemantic=effectiveRepresentationMode!==undefined,primitiveGlow=isSemantic?"#365B82":PRIMITIVE_GLOW[visualPrimitive]??"#365B82",field=isSemantic?{}:backgroundField(visualPrimitive,primitiveGlow),isPayoff=visualOperation==="payoff",showTitle=compositionMode==="bookend"&&!isPayoff,showInteraction=!isSemantic&&compositionMode==="reaction"&&characterCutIn!=="none",compositionScale=compositionMode==="full-model"?(isPayoff?1.18:1.26):compositionMode==="reaction"?1.08:compositionMode==="bookend"?1.14:1.06,scaledWidth=`${100/compositionScale}%`,scaledHeight=Math.round(510*compositionScale),motionMode=compositionMode==="full-model"&&rendererDiagnosticMode==="normal"?"foreground-only":rendererDiagnosticMode;
  return <AbsoluteFill style={{background:`radial-gradient(circle at 24% 22%,${primitiveGlow}66 0,${BG} 48%,#070A12 100%)`,fontFamily:"Inter,Arial,sans-serif",overflow:"hidden"}}><div style={{position:"absolute",inset:0,opacity:.24,...field}}/><CharacterModelInteraction operation={visualOperation} state={visualState} visible={showInteraction}/><CompositionFrame mode={compositionMode} characters={safeCharacters} cutIn={characterCutIn} opacity={progress}>{showTitle?<Title>{title}</Title>:null}{!isPayoff&&characterDominant&&keyText?<div style={{color:PAPER,fontSize:48,lineHeight:1.05,fontWeight:860,borderLeft:`10px solid ${ACCENT}`,padding:"16px 28px",marginBottom:24}}>{keyText}</div>:null}<div style={{position:"relative",width:"100%",minHeight:scaledHeight,display:"grid",placeItems:"center"}}>{isSemantic?<SemanticScene representationMode={effectiveRepresentationMode} sceneBlueprint={effectiveBlueprint} visualClaim={effectiveClaim} semanticActionWindows={effectiveWindows} semanticEntities={effectiveEntities} elements={elements} before={before} after={after} keyText={keyText} numericValue={numericValue}/>:<><div style={{position:"relative",opacity:isPayoff ? .22 : 1,width:scaledWidth,transform:`scale(${compositionScale})`,transformOrigin:"center center"}}><MotionDesignSystem diagnosticMode={motionMode} primitive={visualPrimitive} operation={visualOperation} state={visualState} numericValue={numericValue} elements={elements} entityIdentityKeys={entityIdentityKeys} entityIcons={entityIcons} modelRelations={modelRelations} before={before} after={after} keyText={keyText}/></div>{isPayoff?<PayoffResolution after={after} keyText={keyText} elements={elements} entityIdentityKeys={entityIdentityKeys} entityIcons={entityIcons}/>:null}</>}</div></CompositionFrame></AbsoluteFill>;
};
