import React from "react";
import {interpolate,useCurrentFrame,useVideoConfig} from "remotion";

export type RepresentationMode="concrete-scene"|"domain-model"|"quantitative"|"spatial"|"kinetic-text";
export type SceneBlueprint="container-object"|"molecular-system"|"lattice"|"cross-section"|"mass-volume-comparison"|"before-after-object"|"animated-statement";
export interface SemanticActionWindow{actor:string;action:string;target:string;startRatio:number;endRatio:number;aligned:boolean}
export interface SemanticSceneProps{representationMode?:RepresentationMode;sceneBlueprint?:SceneBlueprint;visualClaim?:string;semanticActionWindows?:SemanticActionWindow[];elements?:string[];before?:string;after?:string;keyText?:string;numericValue?:number|null}

const PAPER="#F7F4EA",ACCENT="#FFD166",BLUE="#65C7F7",GREEN="#7DE2A8",RED="#FF7D7D",TEAL="#5DE0C6",BG="#08101E";
export const SUPPORTED_SEMANTIC_BLUEPRINTS=new Set<SceneBlueprint>(["container-object","molecular-system","lattice","cross-section","mass-volume-comparison","before-after-object","animated-statement"]);
export function semanticBlueprintFitsMode(m?:RepresentationMode,b?:SceneBlueprint){if(!m||!b)return false;if(m==="concrete-scene")return b==="container-object"||b==="before-after-object";if(m==="domain-model")return b==="molecular-system"||b==="lattice";if(m==="quantitative")return b==="mass-volume-comparison";if(m==="spatial")return b==="cross-section";return b==="animated-statement"}
function ratio(){const f=useCurrentFrame(),{durationInFrames:d}=useVideoConfig();return Math.max(0,Math.min(1,f/Math.max(1,d-1)))}
function p(r:number,w?:SemanticActionWindow){if(!w)return 0;return Math.max(0,Math.min(1,(r-w.startRatio)/Math.max(.001,w.endRatio-w.startRatio)))}
function ap(r:number,a:SemanticActionWindow[],names:string[]){return Math.max(0,...a.filter(x=>names.includes(x.action)).map(x=>p(r,x)))}
function claim(x:SemanticSceneProps){return (x.visualClaim||x.keyText||x.after||x.before||x.elements?.[0]||"Main idea").trim()}

function Statement(x:SemanticSceneProps){const r=ratio();return <div data-semantic-blueprint="animated-statement" style={{minHeight:520,display:"grid",placeItems:"center",padding:"30px 80px",textAlign:"center"}}><div><div style={{fontSize:76,lineHeight:1.04,fontWeight:920,color:PAPER,transform:`translateY(${(1-Math.min(1,r/.18))*30}px)`,opacity:Math.min(1,r/.12)}}>{claim(x)}</div><div style={{height:8,width:`${Math.min(1,r/.55)*620}px`,maxWidth:"70vw",margin:"28px auto 0",borderRadius:8,background:GREEN}}/></div></div>}

function Container(x:SemanticSceneProps){const r=ratio(),a=x.semanticActionWindows||[],drop=ap(r,a,["drop","enter"]),rise=ap(r,a,["rise"]),sink=ap(r,a,["sink"]),settle=ap(r,a,["settle"]);let y=75+205*(drop||1);if(rise)y-=130*rise;if(sink)y+=135*sink;if(settle&&rise)y=150+Math.sin(settle*Math.PI)*8;const obj=x.elements?.[0]||"object",medium=x.elements?.[1]||"medium";return <svg data-semantic-blueprint="container-object" viewBox="0 0 1100 520" style={{width:"100%",maxWidth:1450}}><path d="M270 80 L320 455 Q325 480 360 480 H740 Q775 480 780 455 L830 80" fill="#0C1C31" stroke={BLUE} strokeWidth="9"/><path d="M315 190 H785 L752 450 H348 Z" fill="#163A5C"/><path d="M315 190 Q450 178 550 190 T785 190" fill="none" stroke={TEAL} strokeWidth="7"/><g transform={`translate(550 ${y})`}><rect x="-66" y="-66" width="132" height="132" rx="30" fill="#FFD16655" stroke={ACCENT} strokeWidth="8"/><circle r="24" fill={ACCENT}/></g><text x="550" y="45" fill={ACCENT} fontSize="38" fontWeight="900" textAnchor="middle">{obj}</text><text x="925" y="250" fill={TEAL} fontSize="34" fontWeight="850" textAnchor="middle">{medium}</text>{(rise>.05||sink>.05)&&<path d={rise>sink?"M190 320 L190 185 M170 210 L190 180 L210 210":"M190 185 L190 330 M170 305 L190 335 L210 305"} fill="none" stroke={rise>sink?GREEN:RED} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>}</svg>}

function Particle({x,y,rot=0,scale=.7}:{x:number;y:number;rot?:number;scale?:number}){return <g transform={`translate(${x} ${y}) rotate(${rot}) scale(${scale})`}><circle r="42" fill={BLUE} stroke={PAPER} strokeWidth="6"/><circle cx="-28" cy="-18" r="12" fill={ACCENT}/><circle cx="25" cy="20" r="10" fill={GREEN}/></g>}
function Molecular(x:SemanticSceneProps){const r=ratio(),a=x.semanticActionWindows||[],slow=ap(r,a,["slow","cool"]),bond=ap(r,a,["bond","connect"]),arr=ap(r,a,["rearrange","assemble","cluster"]);const from=[[170,140],[435,110],[760,150],[285,350],[600,335],[900,350]],to=[[210,150],[475,150],[740,150],[340,350],[605,350],[870,350]];const pts=from.map(([px,py],i)=>[px+(to[i]![0]-px)*arr+Math.sin(r*18+i)*22*(1-slow),py+(to[i]![1]-py)*arr+Math.cos(r*15+i)*18*(1-slow)]);return <svg data-semantic-blueprint="molecular-system" viewBox="0 0 1100 520" style={{width:"100%",maxWidth:1450}}>{pts.slice(0,-1).map(([px,py],i)=><line key={i} x1={px+45} y1={py+25} x2={pts[i+1]![0]-45} y2={pts[i+1]![1]+25} stroke={TEAL} strokeWidth="6" strokeDasharray="13 12" opacity={bond}/>) }{pts.map(([px,py],i)=><Particle key={i} x={px} y={py} rot={(i%2?-18:20)*(1-arr)}/>) }<text x="550" y="505" fill={PAPER} fontSize="34" fontWeight="800" textAnchor="middle">{claim(x)}</text></svg>}

function Lattice(x:SemanticSceneProps){const r=ratio(),a=x.semanticActionWindows||[],build=ap(r,a,["assemble","rearrange","bond"]),expand=ap(r,a,["expand","reveal"]),cx=550,cy=245,rx=125+80*Math.max(build,expand),ry=100+55*Math.max(build,expand);const pts=Array.from({length:6},(_,i)=>{const q=-Math.PI/2+i*Math.PI/3;return[cx+Math.cos(q)*rx,cy+Math.sin(q)*ry]});return <svg data-semantic-blueprint="lattice" viewBox="0 0 1100 520" style={{width:"100%",maxWidth:1450}}>{pts.map(([px,py],i)=><line key={`e${i}`} x1={px} y1={py} x2={pts[(i+1)%6]![0]} y2={pts[(i+1)%6]![1]} stroke={TEAL} strokeWidth="7" strokeDasharray="14 12" opacity={build}/>) }{pts.map(([px,py],i)=><Particle key={i} x={cx+(px-cx)*Math.max(.25,build)} y={cy+(py-cy)*Math.max(.25,build)} rot={i*60} scale={.55}/>) }<ellipse cx={cx} cy={cy} rx={rx*.4} ry={ry*.35} fill="#65C7F712" stroke={ACCENT} strokeWidth="5" strokeDasharray="12 10" opacity={expand}/><text x="550" y="505" fill={PAPER} fontSize="34" fontWeight="800" textAnchor="middle">{claim(x)}</text></svg>}

function Cross(x:SemanticSceneProps){const r=ratio(),a=x.semanticActionWindows||[],sink=ap(r,a,["sink"]),rise=ap(r,a,["rise"]),freeze=ap(r,a,["freeze","transform"]),flow=ap(r,a,["flow","move"]);return <svg data-semantic-blueprint="cross-section" viewBox="0 0 1100 520" style={{width:"100%",maxWidth:1450}}><path d="M80 145 Q210 90 330 135 T560 125 T820 130 T1020 120 L1020 460 L80 460 Z" fill="#163A5C" stroke={BLUE} strokeWidth="7"/><path d="M80 145 Q210 90 330 135 T560 125 T820 130 T1020 120" fill="none" stroke={TEAL} strokeWidth="8"/><rect x="80" y="145" width="940" height={38*freeze} fill="#DDF6FF" opacity={freeze}/><ellipse cx={380+flow*90} cy={200+sink*145-rise*60} rx="75" ry="36" fill="#65C7F766" stroke={BLUE} strokeWidth="5"/><ellipse cx={720-flow*70} cy={345-rise*100+sink*30} rx="80" ry="38" fill="#7DE2A84A" stroke={GREEN} strokeWidth="5"/><text x="550" y="505" fill={PAPER} fontSize="34" fontWeight="800" textAnchor="middle">{claim(x)}</text></svg>}

function Volume(x:SemanticSceneProps){const r=ratio(),a=x.semanticActionWindows||[],e=ap(r,a,["expand","compare","rearrange"]),dots=Array.from({length:12},(_,i)=>i),box=(bx:number,by:number,w:number,h:number,prefix:string)=><>{<rect x={bx} y={by} width={w} height={h} rx="28" fill="#0C1C31" stroke={prefix==="L"?BLUE:GREEN} strokeWidth="7"/>}{dots.map(i=>{const col=i%4,row=Math.floor(i/4);return <circle key={prefix+i} cx={bx+55+col*(w-110)/3} cy={by+60+row*(h-120)/2} r="14" fill={ACCENT}/>})}</>;return <svg data-semantic-blueprint="mass-volume-comparison" viewBox="0 0 1100 520" style={{width:"100%",maxWidth:1450}}>{box(90,110,340,300,"L")}{box(610-e*55,90-e*20,340+e*150,300+e*40,"R")}<text x="260" y="70" fill={BLUE} fontSize="35" fontWeight="900" textAnchor="middle">same amount</text><text x="810" y="70" fill={GREEN} fontSize="35" fontWeight="900" textAnchor="middle">more volume</text><text x="550" y="500" fill={PAPER} fontSize="33" fontWeight="800" textAnchor="middle">{claim(x)}</text></svg>}

function BeforeAfter(x:SemanticSceneProps){const r=ratio(),a=x.semanticActionWindows||[],t=Math.max(.05,ap(r,a,["transform","freeze","melt","rearrange","assemble","disassemble"])),b=x.before||x.elements?.[0]||"before",after=x.after||x.elements?.[1]||"after";return <svg data-semantic-blueprint="before-after-object" viewBox="0 0 1100 520" style={{width:"100%",maxWidth:1450}}><rect x="70" y="90" width="410" height="350" rx="32" fill="#0C1C31" stroke={BLUE} strokeWidth="7"/><rect x="620" y="90" width="410" height="350" rx="32" fill="#0C1C31" stroke={GREEN} strokeWidth="7" opacity={.3+.7*t}/><circle cx="275" cy="250" r="90" fill="#65C7F733" stroke={BLUE} strokeWidth="8"/><circle cx="825" cy="250" r={82+25*t} fill="#7DE2A833" stroke={GREEN} strokeWidth="8" opacity={.3+.7*t}/><path d="M500 250 L590 250 M570 230 L595 250 L570 270" fill="none" stroke={ACCENT} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/><text x="275" y="410" fill={PAPER} fontSize="36" fontWeight="850" textAnchor="middle">{b}</text><text x="825" y="410" fill={PAPER} fontSize="36" fontWeight="850" textAnchor="middle">{after}</text></svg>}

export const SemanticScene:React.FC<SemanticSceneProps>=(x)=>{const valid=semanticBlueprintFitsMode(x.representationMode,x.sceneBlueprint)&&!!x.sceneBlueprint&&SUPPORTED_SEMANTIC_BLUEPRINTS.has(x.sceneBlueprint),withActions=(x.semanticActionWindows?.length||0)>0;let b:SceneBlueprint=valid?x.sceneBlueprint!:"animated-statement";if(b!=="animated-statement"&&!withActions)b="animated-statement";const content=b==="container-object"?<Container {...x}/>:b==="molecular-system"?<Molecular {...x}/>:b==="lattice"?<Lattice {...x}/>:b==="cross-section"?<Cross {...x}/>:b==="mass-volume-comparison"?<Volume {...x}/>:b==="before-after-object"?<BeforeAfter {...x}/>:<Statement {...x}/>;return <div data-semantic-renderer="true" data-semantic-effective-blueprint={b} style={{width:"100%",minHeight:540,display:"grid",placeItems:"center",background:`radial-gradient(ellipse at 50% 48%,#16324A55 0%,${BG}00 65%)`}}>{content}</div>}
